# Generated by Django 3.2.7 on 2021-09-26 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210923_1936'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishList',
        ),
    ]
