# Generated by Django 3.2.7 on 2021-09-06 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_sold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='condition',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='noteone',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='notes',
            new_name='overview',
        ),
        migrations.RemoveField(
            model_name='product',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sold',
        ),
    ]
