# Generated by Django 3.2.7 on 2021-09-26 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_delete_wishlist'),
        ('products', '0006_productwishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductWishList',
        ),
    ]
